POST http://localhost:7111/addbooks
Content-Type: application/json


{
    "title":"title1",
    "genre":"genre1",
    "author":"author1",
    "publisher":"publisher1",
    "stock":1000,
     "Adminid":1
    
    
 
}
